export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const OPEN_INGREDIENT_DETAILS = "OPEN_INGREDIENT_DETAILS";
export const OPEN_ORDER_DETAILS = "OPEN_ORDER_DETAILS";
export const SHUT_DOWN_MODAL = "SHUT_DOWN_MODAL";