export const SAVE_INGREDIENTS = "SAVE_INGREDIENTS";
export const LOAD_INGREDIENTS = "LOAD_INGREDIENTS";
export const ERROR_ON_LOAD = "ERROR_ON_LOAD";
export const INGREDIENTS_LOADED = "INGREDIENTS_LOADED";