export const SAVE_INGREDIENTS = "SAVE_INGREDIENTS";
export const INGREDIENTS_REQUEST = "LOAD_INGREDIENTS";
export const INGREDIENTS_ERROR = "ERROR_ON_LOAD";
export const INGREDIENTS_SUCCESS = "INGREDIENTS_LOADED";